runtime: nodejs22
service: notes-frontend

# Skala otomatis (gratis)
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

# Handler untuk file statis
handlers:
  # File JavaScript
  - url: /script.js
    static_files: script.js
    upload: script.js

  # File CSS
  - url: /style.css
    static_files: style.css
    upload: style.css

  # Semua request lain ke index.html
  - url: /.*
    static_files: index.html
    upload: index.html