- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "run",
      "deploy",
      "be-rest",
      "--image",
      "gcr.io/$PROJECT_ID/tcc-be-rest",
      "--timeout",
      "1000s",
      "--region",
      "asia-southeast1",
      "--allow-unauthenticated",
      "--set-env-vars",
      "DB_HOST=34.172.113.167,DB_USER=admin,DB_PASSWORD=mypassword,DB_NAME=notes_123230002,PORT=8080"
    ]